version: '2'
services:    
  app:
    container_name: hybyrd 
    image: hybyrd
    env_file: hybyrd.env
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  
    volumes:
      - './:/app'  
 